// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:87dc5b38-1b68-4e7b-a3ad-e26dd24cf56f',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_vJM2DJbgL',
  aws_user_pools_web_client_id: '5cmdnqntii5adcsote0hbc6si3',
  oauth: {
    domain: 'idcrypt-dev.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: 'https://dev.idcrypt.io/',
    redirectSignOut: 'https://dev.idcrypt.io/login/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'idcryptui2c42702b48354906b27294d6a76c15a6184514-dev',
  aws_user_files_s3_bucket_region: 'eu-west-1'
};


export default awsmobile;
