// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:15dcfd01-23d5-4e4a-ad46-8e327c3345ff",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_W7ood2PZl",
    "aws_user_pools_web_client_id": "641h9602v3ep81fqege0rt5qf2",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "idcryptui2c42702b48354906b27294d6a76c15a6184514-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
