// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:15b81e0f-03a3-4904-ac2f-443af00470a5',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_pOQz5nJN1',
  aws_user_pools_web_client_id: '4nbk46md8imle80qhcae8jkptc',
  oauth: {
    domain: 'dev-idcrypt-dev.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: 'https://dev.idcrypt.io/',
    redirectSignOut: 'https://dev.idcrypt.io/login/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'idcryptui2c42702b48354906b27294d6a76c15a6184514-dev',
  aws_user_files_s3_bucket_region: 'eu-west-1'
};


export default awsmobile;
